### PR TITLE
Improved Chinese localization

### PR DESCRIPTION
**Pull request by loikein**
Thanks for creating the great app. 
I have written a review through the App Store asking how to help improving localization, and figured out that you are using GitHub. Perfect! 
I will try to continue doing this as long as I find anything while using the app.

### CODE REVIEW

**Comment by kolyvan** [comment]
Thank you very much for PR, I will review it as soon as possible

**Comment by kolyvan** [comment]
Hi, I have several remarks about your suggested changes.

**reader.general**
Current variant is  `读者`, your suggest `阅读`
Google translated  `读者` as `Reader` and `阅读` as `read or reading`.
In KyBook meanings, **reader.general** is title of the Reader module or feature. There are some other modules like Cache, File store, Cataloguer, etc.  **reader.general** is not a verb, this is a noun and describes of one of the application module.

**app.prefs.cache.reader**
now `读者缓存`, your `书籍缓存`.
By Google `读者缓存` is `Reader cache` and `书籍缓存` is `Book cache`.
Yes, both variants are possible. But **app.prefs.cache.reader** as ``读者缓存` is more convenient title since it describes a size of cached files made by Reader module. 

**imagepicker.photo.notdetermined**
The translation `未选择照片` by Google is `No photos selected`. This is not right meaning of **imagepicker.photo.notdetermined**. The **imagepicker.photo.notdetermined** is when an user is not yet decided to allow or not to allow KyBook to accessing Photos.

**reader.settings.lineheight**
now `线高` (Line height your `行高` (Row height).
I am unsure which of Chinese version is right.
In the typography based on the Latin languages , the correct term is `Line height`. The `Row height` is not used for texts. But I am unsure about Chinese typography.

**reader.settings.override**
You suggest `覆盖图书自带格式` as an equivalent for the English word `Override`.
Google translates `覆盖图书自带格式` as `Cover the book's own format` 
Seems Google is completely wrong here, I don't know.
**reader.settings.override** is a verb and the sample of using  is 'Override the settings'
Seems that current variant `覆盖` is more suitable? Or maybe `覆盖设置` ?

**"theme.pallete.control"**
Your suggestion is `设置` (Setting) is not valid.
**"theme.pallete.control"** is a term of the color of some UI elements (cells, buttons, etc).
Current localization `控制` seems more correct.

**Comment by loikein** [comment]
Thank you for your reviews. I have some remarks and I will commit the changes into my fork.

## reader.general
- Current variant is `读者`, your suggest `阅读`, Google translated 读者 as Reader and 阅读 as read or reading.

`读者` means explicitly "reading person" in Chinese, not "reading interface". Or I can also accept `阅读器` which literally means "reading interface".

## app.prefs.cache.reader
- now `读者缓存`, your `书籍缓存`. By Google 读者缓存 is Reader cache and 书籍缓存 is Book cache.

As stated above, `读者` means explicitly "reading person". `读者缓存` is not a proper word. 

## imagepicker.photo.notdetermined
- The translation 未选择照片 by Google is No photos selected. This is not right meaning of imagepicker.photo.notdetermined. The imagepicker.photo.notdetermined is used when an user is not yet decided to allow or disallow KyBook accessing Photos.

The current `您尚未对KyBook做出选择` means "you have not make a choice for KyBook" which is not a proper sentence. Since I have not used this fuction, I do not know what is the context of it. 
After reading your explanation, I think `您尚未授权KyBook读取照片` can be a plausible alternative. 

## reader.settings.lineheight
- now 线高 (Line height your 行高 (Row height).

As you pointed out, `line height` is a typographical word and we normally use `行高` for it. `线高` is not a proper word as far as I am informed. 

## reader.settings.override

`覆盖设置` is good. 

## "theme.pallete.control"
- "theme.pallete.control" is a term of the color of some UI elements (cells, buttons, etc). Current localization 控制 seems more correct.

This is acually the very trigger that I decided to contribute. `控制` means controlling or ruling (by someone, something). It is a word unusual to appear in any app, and I strongly suggest that you use `设置`.

**Comment by kolyvan** [comment]
Thank you very much for the detailed explanation.

**Pull request merged**
